name: hola-proxy
version: '1.4.3'
summary: Standalone Hola proxy client.
description: |
  Standalone Hola proxy client. Just run it and it'll start plain HTTP proxy server forwarding traffic via Hola proxies of your choice.

confinement: strict
base: core18

parts:
  hola-proxy:
    plugin: go
    go-importpath: github.com/Snawoot/hola-proxy
    source: https://github.com/Snawoot/hola-proxy
    source-type: git
    build-packages:
      - gcc

apps:
  hola-proxy:
    command: bin/hola-proxy
    plugs:
      - network
      - network-bind
